commit_message: '[ci skip]'
files:
  - source: /Cryptomator/en.lproj/Localizable.strings
    translation: /Cryptomator/%osx_code%/%original_file_name%
    skip_untranslated_files: true
  - source: /FileProviderExtensionUI/en.lproj/Localizable.strings
    translation: /FileProviderExtensionUI/%osx_code%/%original_file_name%
    skip_untranslated_files: true
  - source: /SharedResources/en.lproj/Localizable.strings
    translation: /SharedResources/%osx_code%/%original_file_name%
    skip_untranslated_files: true
