commit_message: '[ci skip]'
files:
  - source: /Cryptomator/en.lproj/Localizable.strings
    translation: /Cryptomator/%two_letters_code%.lproj/Localizable.strings
  - source: /FileProviderExtensionUI/en.lproj/Localizable.strings
    translation: /FileProviderExtensionUI/%two_letters_code%.lproj/Localizable.strings
