name: Build

on:
  [push]

jobs:
  build:
    name: Build and test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install dependencies
        run: pod install
      - name: Build and test CloudAccessPrivate
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace 'Cryptomator.xcworkspace' -scheme 'CloudAccessPrivate' -destination 'name=iPhone 11 Pro' clean test | xcpretty
        env:
          GOOGLE_DRIVE_CLIENT_ID: ${{ secrets.GOOGLE_DRIVE_CLIENT_ID }}
          GOOGLE_DRIVE_REDIRECT_URL: ${{ secrets.GOOGLE_DRIVE_REDIRECT_URL }}
      - name: Run CryptomatorIntegrationTests
        if: startsWith(github.ref, 'refs/tags/')
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace 'Cryptomator.xcworkspace' -scheme 'CryptomatorIntegrationTests' -destination 'name=iPhone 11 Pro' test | xcpretty
        env:
          GOOGLE_DRIVE_REFRESH_TOKEN: ${{ secrets.GOOGLE_DRIVE_REFRESH_TOKEN }}
      - name: Build and test Cryptomator
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace 'Cryptomator.xcworkspace' -scheme 'Cryptomator' -destination 'name=iPhone 11 Pro' test | xcpretty
