name: Build

on:
  [push]

jobs:
  build:
    name: Build and test
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Run process.sh script
        run: |
          ./Scripts/process.sh
          exit $?
      - name: Create CloudAccessSecrets
        run: ./create-cloud-access-secrets-file.sh
      - name: Build and test
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme 'AllTests' -destination 'name=iPhone 12 Pro' -enableCodeCoverage YES clean test | xcpretty
      - name: Upload code coverage report
        run: |
          gem install slather
          slather coverage -x -i '../../../Library/*' --scheme AllTests Cryptomator.xcodeproj
          bash <(curl -Ls https://coverage.codacy.com/get.sh)
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        continue-on-error: true
