name: Build

on:
  [push]
env:
  DERIVED_DATA_PATH: 'DerivedData'
  DEVICE: 'iPhone 12 Pro'

jobs:
  build:
    name: Build and test
    runs-on: macos-12
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        version: ['Freemium', 'Premium']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Run process.sh script
        run: |
          ./Scripts/process.sh
          exit $?
      - name: Create CloudAccessSecrets
        run: |
          cd fastlane
          ./scripts/create-cloud-access-secrets.sh
      - name: Configuration for Freemium
        if: ${{ matrix.version == 'Freemium' }}
        run: |
          echo "BUILD_CMD=-enableCodeCoverage YES" >> $GITHUB_ENV
      - name: Configuration for Premium
        if: ${{ matrix.version == 'Premium' }}
        run: |
          echo "BUILD_CMD=SWIFT_ACTIVE_COMPILATION_CONDITIONS='\$(inherited) ALWAYS_PREMIUM'" >> $GITHUB_ENV
      - name: Build
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild clean build-for-testing -scheme 'AllTests' -destination "name=$DEVICE" -derivedDataPath $DERIVED_DATA_PATH ${{ env.BUILD_CMD }} | xcpretty
      - name: Test
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -xctestrun $(find . -type f -name "*.xctestrun") -destination "name=$DEVICE" -derivedDataPath $DERIVED_DATA_PATH | xcpretty
      - name: Upload code coverage report
        if: ${{ matrix.version == 'Freemium' }}
        run: |
          gem install slather
          slather coverage -x  --build-directory $DERIVED_DATA_PATH --ignore "$DERIVED_DATA_PATH/SourcePackages/*" --scheme AllTests Cryptomator.xcodeproj
          bash <(curl -Ls https://coverage.codacy.com/get.sh)
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        continue-on-error: true
  
